name: Build Weekly Report

on:
  schedule:
    - cron: "0 6 * * 6"  # Saturdays 06:00 UTC; adjust if needed
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy scipy pandas_datareader
      - name: Generate HTML
        run: python dashboard.py
      - name: Publish artifact to branch
        run: |
          mkdir -p public
          cp report.html public/index.html
          echo "report built on $(date -u)" > public/build.txt
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
